### Arrays:
It is an ordered collection of elements with every value being of the same data type.

In [2]:
#Create an array
import numpy as np
arr=np.array([1,3,5,7,9])
print(arr)

[1 3 5 7 9]


In [4]:
#Use a tuple to create a numpy array
import numpy as np
arr=np.array((1,3,5,7,9))
print(arr)

[1 3 5 7 9]


### Dimension in arrays

#### 0-D arrays
0-D arrays are the elements in an array.Each value in an array is a 0-D.

In [6]:
import numpy as np 
arr=np.array(28)
print(arr)

28


#### 1-D arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [7]:
import numpy as np
arr=np.array([1,2,4,6,7])
print(arr)

[1 2 4 6 7]


#### 2-D arrays
An array that has 1-D arrays as its elements is called 2-D array.

In [8]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### 3-D arrays
An array that has 2-D arrays as its elements is called 3-D array.

In [9]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Checking number of dimensions

In [10]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr.ndim)

3


In [11]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


### Higher Dimensional Arrays

In [12]:
arr=np.array([2,4,6,8],ndmin=5)
print(arr)

[[[[[2 4 6 8]]]]]


### Array Indexing

#### Access array elements

In [13]:
arr=np.array([1,2,4,6,7])
print(arr[2])

4


In [15]:
#add third and fourth elements
arr=np.array([1,2,4,6,7])
print(arr[2]+arr[3])

10


#### Access 2-D Arrays

In [18]:
#access the element on second row and third column
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[1,2])

[[1 2 3]
 [4 5 6]]
6


### Array Slicing

In [3]:
arr=np.array([1,2,4,6,7])
print(arr[1:4])

[2 4 6]


In [4]:
arr=np.array([1,2,4,6,7])
print(arr[2:])

[4 6 7]


In [5]:
arr=np.array([1,2,4,6,7])
print(arr[-5:-1])

[1 2 4 6]


In [6]:
arr=np.array([2,4,6,5,8,9,1])
print(arr[1:5:2])

[4 5]


In [7]:
arr=np.array([2,4,6,5,8,9,1])
print(arr[1:5:3])


[4 8]


In [8]:
arr=np.array([2,4,6,5,8,9,1])
print(arr[::2])

[2 6 8 1]


In [11]:
#access the element on the second row ,third column
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,2])

8


### Numpy Array Shape
The shape of an array is the number of elements in each dimension.

In [12]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


### Reshaping Arrays
Reshaping means changing the shape of an array.

In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### Reshape from 1-D to 3-D 

In [3]:
#convert the following 1-D array with 12 elements into a 3-D array.
#The outermost dimensions will have 2 arrays that contains 3 arrays,each withh 2 elements.
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Iterating Arrays
Iterating means going through element one by one.If we iterate on a n-D array it will go through n-1th dimension one by one.

In [6]:
arr=np.array([1,3,5,7])
for i in arr:
    print(i)

1
3
5
7


In [7]:
#Iterating 2-D array
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


To return actual values, the scalars,we have to iterate the arrays in each dimension.

In [8]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [11]:
#Iterating 3-D array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [10]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### Joining Array

In [13]:
arr1=np.array([1,3,5])
arr2=np.array([2,4,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 3 5 2 4 6]


In [15]:
#Join 2-D arrays along rows(axis=1):
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [19]:

arr1=np.array([1,3,5])
arr2=np.array([2,4,6])
arr=np.stack((arr1,arr2),axis=0)
print(arr)

[[1 3 5]
 [2 4 6]]


In [20]:
arr1=np.array([1,3,5])
arr2=np.array([2,4,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 2]
 [3 4]
 [5 6]]


### Splitting Arrays
Splitting is reverse operation of joining.Splitting breaks one array into multiple.

In [21]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


### Searching Arrays
You can search an array for a certain value ,and return the indexes that get a match.To search an array,use the where() method.

In [22]:
#Find the indexes where the value is 4
arr=np.array([1,2,3,4,6,4])
x=np.where(arr==4)
print(x)

(array([3, 5], dtype=int64),)


In [24]:
#Find the indexes where the values are even.
arr=np.array([1,2,3,4,6,4])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 4, 5], dtype=int64),)


In [25]:
#Find the indexes where the values are even.
arr=np.array([1,2,3,4,6,4])
x=np.where(arr%2==1)
print(x)

(array([0, 2], dtype=int64),)


### Sorting Arrays
Sorting means putting elements in an ordered sequence.

In [26]:
arr=np.array([5,6,8,2,4])
print(np.sort(arr))

[2 4 5 6 8]


In [27]:
#Sorting 2-D array
arr=np.array([[3,2,1],[5,2,8]])
print(np.sort(arr))

[[1 2 3]
 [2 5 8]]


### Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.In NumPy,We filter an array using a boolean index list.
A boolean index list is a list of booleans corresponding to indexes in the array.If the value at an index is True that element is contained in the filtered array,if the value at that index is False that element is excluded from the filtered array.

In [1]:
#Create an array from the elements on index 0 and 2.
import numpy as np
arr=np.array([20,40,60,80])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[20 60]


In [2]:
#Create a filter array that will return only values higher than 38:
arr=np.array([40,20,45,10,50])
filter_arr=[]
for element in arr:
    if element>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, False, True]
[45 50]


In [4]:
#Creating Filter Directly from Array
arr=np.array([40,20,45,10,50])
filter_arr=arr>42
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True False  True]
[45 50]
